capture:
  fs: 2000000
  fc: 503000000
  device:
    type: "RspDuo"
    agcSetPoint: -60
    bandwidthNumber: 0
    gainReduction: 40 #20-59 dB, higher is less gain
    lnaState: 4 #1-9, higher is more gain
    dabNotch: true
    rfNotch: true
  replay:
    state: false
    loop: true
    file: '/opt/blah2/replay/file.rspduo'

process:
  data:
    cpi: 0.5
    buffer: 1.5
    overlap: 0
  ambiguity:
    delayMin: -10
    delayMax: 400
    dopplerMin: -200
    dopplerMax: 200
  clutter:
    enable: true
    delayMin: -10
    delayMax: 400
  detection:
    enable: true
    pfa: 0.00001
    nGuard: 2
    nTrain: 6
    minDelay: 5
    minDoppler: 15
    nCentroid: 6
  tracker:
    enable: true
    initiate:
      M: 3
      N: 5
      maxAcc: 10
    delete: 10
    smooth: "none"

network:
  ip: 0.0.0.0
  ports:
    api: 3000
    map: 3001
    detection: 3002
    track: 3003
    timestamp: 4000
    timing: 4001
    iqdata: 4002
    config: 4003

  node_id: "ret7dd2cb0d"

truth:
  adsb:
    enabled: true
    tar1090: 'sfo1.retnode.com'
    adsb2dd: 'localhost:49155'
  ais:
    enabled: false
    ip: 0.0.0.0
    port: 30001

location:
  rx:
    latitude: 37.7644
    longitude: -122.3954
    altitude: 23
    name: "150 Mississippi"
  tx:
    latitude: 37.49917
    longitude: -121.87222
    altitude: 783
    name: "KSCZ-LD"

save:
  iq: false
  map: false
  detection: true
  timing: false
  path: "/blah2/save/"
